<h1>Welcome to the Phalcon Boilerplate!</h1>
<p>
    Phalcon Boilerplate is a template for building large-scale
    PhalconPHP applications. It contains the structure and configuration
    for managing a big project.
</p>

<fieldset>
    <legend>
        <h2>Quickstart Guide</h2>
    </legend>
    <p>
        View the README (<a href="https://github.com/mikegioia/phalcon-boilerplate/README">here</a>
        or in the application root directory) for a quick guide to getting everything
        installed and running correctly.
    </p>
</fieldset>

<fieldset>
    <legend>
        <h2>Source Code</h2>
    </legend>
    <ul>
        <li>
            <a href="https://bitbucket.com/mikegioia/phalcon-boilerplate">Bitbucket repository (hg)</a>
        </li>
        <li>
            <a href="https://github.com/mikegioia/phalcon-boilerplate">Github repository (git)</a>
        </li>
    </ul>
</fieldset>

<fieldset>
    <legend>
        <h2>Documentation</h2>
    </legend>
    <ul>
        <li>
            <a href="https://particlebits.com/phalcon-boilerplate-part-1-installation">
                Part 1: Installation and Configuration
            </a>
        </li>
        <li>
            <a href="https://particlebits.com/phalcon-boilerplate-part-2-architecture">
                Part 2: Application architecture
            </a>
        </li>
        <li>
            <a href="https://particlebits.com/phalcon-boilerplate-part-3-testing">
                Part 3: Unit testing
            </a>
        </li>
    </ul>
</fieldset>

<fieldset>
    <legend>
        <h2>Login Example</h2>
    </legend>
    <p>
        This boilerplate contains a sample authentication library.
        <a href="<?php echo $this->url->get( 'login' ); ?>">Log in</a> to the application.
    </p>
</fieldset>

<fieldset>
    <legend>
        <h2>REST API Example</h2>
    </legend>
    <ul id="rest">
        <li>
            <a href="#rest" data-url="<?php echo $this->url->get( 'api/auth/login' ); ?>"
                data-params='{"email":"test@example.org","password":"password"}' data-method="POST">
                POST /api/auth/login
            </a>
        </li>
        <li>
            <a href="#rest" data-url="<?php echo $this->url->get( 'api/auth/logout' ); ?>"
                data-params='{}' data-method="POST">
                POST /api/auth/logout
            </a>
        </li>
        <li>
            <a href="#rest" data-url="<?php echo $this->url->get( 'api/dashboard' ); ?>"
                data-params='{}' data-method="GET">
                GET /api/dashboard
            </a>
        </li>
    </ul>
    <p>
        Response:
    </p>
    <div>
        <pre id="response">Click one of the links above</pre>
    </div>
</fieldset>

<script>
    $( '#rest a' ).on( 'click', function () {
        var $this = $( this );
        $.ajax({
            url: $this.data( 'url' ),
            type: $this.data( 'method' ),
            data: $this.data( 'params' ),
            dataType: 'json',
            success: function ( response ) {
                document.getElementById( 'response').innerHTML = 
                    JSON.stringify( response, undefined, 4 );
            }
        });
    });
</script>