<h1>Welcome to the Phalcon Boilerplate!</h1>
<p>
    Phalcon Boilerplate is a template for building large-scale
    PhalconPHP applications. It contains the structure and configuration
    for managing a big project.
</p>
<p>
    For more information:
</p>
<ul>
    <li>
        <a href="https://bitbucket.com/mikegioia/phalcon-boilerplate">Bitbucket repository (hg)</a>
    </li>
    <li>
        <a href="https://github.com/mikegioia/phalcon-boilerplate">Github repository (git)</a>
    </li>
    <li>Tutorial and documentation:
        <ul>
            <li>
                <a href="https://particlebits.com/phalcon-boilerplate-part-1-installation">
                    Part 1: Installation and Configuration
                </a>
            </li>
            <li>
                <a href="https://particlebits.com/phalcon-boilerplate-part-2-architecture">
                    Part 2: Application architecture
                </a>
            </li>
            <li>
                <a href="https://particlebits.com/phalcon-boilerplate-part-3-testing">
                    Part 3: Unit testing
                </a>
            </li>
        </ul>
    </li>
</ul>
<p>
    This example contains a login system and a simple REST API.
</p>
<ul>
    <li>
        <a href="<?php echo $this->url->get( 'login' ); ?>">Log in</a> to the application</a>
    </li>
    <li>
        Test out the REST API:
        <ul>
            <li>
                <a href="">POST /api/auth/login</a>
            </li>
            <li>
                <a href="">POST /api/auth/logout</a>
            </li>
            <li>
                <a href="">GET /api/dashboard/stats</a>
            </li>
        </ul>
    </li>
</ul>