<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Phalcon Boilerplate</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="<?php echo $this->url->get( 'css/app.css' ); ?>">
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    </head>
    <body>
        <div id="content">
<?php   foreach ( $flashMessages as $message ): ?>
            <div class="message <?php echo key( $message ); ?>"><?php echo current( $message ); ?></div>
<?php   endforeach; ?>
            <?php echo $this->getContent() ?>
        </div>
    </body>
</html>