<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Phalcon Boilerplate</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="<?php echo $this->url->get( 'css/normalize.css' ); ?>">
        <link rel="stylesheet" href="<?php echo $this->url->get( 'css/main.css' ); ?>">
        <link rel="stylesheet" href="<?php echo $this->url->get( 'css/app.css' ); ?>">
    </head>
    <body>
        <div id="content">
            <?php echo $this->getContent() ?>
        </div>
    </body>
</html>